/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Returns the authenticated user with their profile information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user with profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            airtable_record_id: string | null;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "mentee" | "mentor" | "coordinator";
                            /** @enum {string} */
                            reputation_tier?: "bronze" | "silver" | "gold" | "platinum";
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            profile: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                user_id: string;
                                name: string;
                                /** Format: uri */
                                avatar_url?: string | null;
                                title: string | null;
                                company: string | null;
                                bio: string | null;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                            };
                            tags?: {
                                /** Format: uuid */
                                taxonomy_id: string;
                                category: string;
                                value: string;
                                display_name: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        /**
         * Update current user profile
         * @description Updates the authenticated user's profile information
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        bio?: string;
                        title?: string;
                        company?: string;
                    };
                };
            };
            responses: {
                /** @description Updated user with profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            airtable_record_id: string | null;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "mentee" | "mentor" | "coordinator";
                            /** @enum {string} */
                            reputation_tier?: "bronze" | "silver" | "gold" | "platinum";
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            profile: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                user_id: string;
                                name: string;
                                /** Format: uri */
                                avatar_url?: string | null;
                                title: string | null;
                                company: string | null;
                                bio: string | null;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                            };
                            tags?: {
                                /** Format: uuid */
                                taxonomy_id: string;
                                category: string;
                                value: string;
                                display_name: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request - Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a list of users, optionally filtered by role
         */
        get: {
            parameters: {
                query?: {
                    role?: "mentee" | "mentor" | "coordinator";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            airtable_record_id: string | null;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "mentee" | "mentor" | "coordinator";
                            /** @enum {string} */
                            reputation_tier?: "bronze" | "silver" | "gold" | "platinum";
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            profile: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                user_id: string;
                                name: string;
                                /** Format: uri */
                                avatar_url?: string | null;
                                title: string | null;
                                company: string | null;
                                bio: string | null;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                            };
                            tags?: {
                                /** Format: uuid */
                                taxonomy_id: string;
                                category: string;
                                value: string;
                                display_name: string;
                            }[];
                        }[];
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get public user profile
         * @description Returns a user's public profile information by user ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            airtable_record_id: string | null;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "mentee" | "mentor" | "coordinator";
                            /** @enum {string} */
                            reputation_tier?: "bronze" | "silver" | "gold" | "platinum";
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            profile: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                user_id: string;
                                name: string;
                                /** Format: uri */
                                avatar_url?: string | null;
                                title: string | null;
                                company: string | null;
                                bio: string | null;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                            };
                            tags?: {
                                /** Format: uuid */
                                taxonomy_id: string;
                                category: string;
                                value: string;
                                display_name: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get availability blocks for authenticated mentor
         * @description Returns all availability blocks for the authenticated mentor. Only mentors can access this endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of availability blocks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            mentor_id: string;
                            /** @enum {string} */
                            recurrence_pattern: "one_time" | "weekly" | "monthly";
                            start_date: string | null;
                            end_date: string | null;
                            /** Format: date-time */
                            start_time: string;
                            /** Format: date-time */
                            end_time: string;
                            slot_duration_minutes: number;
                            buffer_minutes: number;
                            /** @enum {string} */
                            meeting_type: "online" | "in_person_preset" | "in_person_custom";
                            /** Format: uuid */
                            location_preset_id: string | null;
                            location_custom: string | null;
                            description: string | null;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            /** Format: uuid */
                            created_by: string;
                            /** Format: uuid */
                            updated_by: string;
                        }[];
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Forbidden - User is not a mentor */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to fetch availability blocks */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create availability block (one-time only)
         * @description Creates a new one-time availability block for a mentor. Only mentors can create availability blocks. Recurrence patterns and in-person meeting types are not yet supported.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Availability block data */
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        start_time: string;
                        /** Format: date-time */
                        end_time: string;
                        slot_duration_minutes: ("15" | "30" | "60") | number;
                        /** @default 0 */
                        buffer_minutes?: number;
                        /** @enum {string} */
                        meeting_type: "online";
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Availability block created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            mentor_id: string;
                            /** @enum {string} */
                            recurrence_pattern: "one_time" | "weekly" | "monthly";
                            start_date: string | null;
                            end_date: string | null;
                            /** Format: date-time */
                            start_time: string;
                            /** Format: date-time */
                            end_time: string;
                            slot_duration_minutes: number;
                            buffer_minutes: number;
                            /** @enum {string} */
                            meeting_type: "online" | "in_person_preset" | "in_person_custom";
                            /** Format: uuid */
                            location_preset_id: string | null;
                            location_custom: string | null;
                            description: string | null;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                            /** Format: uuid */
                            created_by: string;
                            /** Format: uuid */
                            updated_by: string;
                        };
                    };
                };
                /** @description Bad Request - Validation error or invalid meeting type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Forbidden - User is not a mentor */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to create availability block */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/availability/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available time slots
         * @description Returns available (non-booked) time slots with mentor information. Supports filtering by mentor, date range, and meeting type.
         */
        get: {
            parameters: {
                query?: {
                    mentor_id?: string;
                    start_date?: string;
                    end_date?: string;
                    meeting_type?: "online" | "in_person";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available time slots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            slots: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                availability_id: string;
                                /** Format: uuid */
                                mentor_id: string;
                                /** Format: date-time */
                                start_time: string;
                                /** Format: date-time */
                                end_time: string;
                                slot_duration_minutes: number;
                                is_booked: boolean;
                                mentor: {
                                    /** Format: uuid */
                                    id: string;
                                    name: string;
                                    /** Format: uri */
                                    avatar_url: string | null;
                                };
                                /** Format: date-time */
                                created_at: string;
                            }[];
                            pagination: {
                                total: number;
                                limit: number;
                                has_more: boolean;
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to fetch available slots */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new booking
         * @description Book a mentor time slot (Epic 0: Simple booking - no calendar integration, no confirmation flow, status always pending)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        time_slot_id: string;
                        meeting_goal: string;
                    };
                };
            };
            responses: {
                /** @description Booking created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            time_slot_id: string;
                            /** Format: uuid */
                            mentor_id: string;
                            /** Format: uuid */
                            mentee_id: string;
                            meeting_goal: string;
                            /** @enum {string} */
                            status: "pending" | "confirmed" | "completed" | "canceled" | "expired";
                            /** Format: date-time */
                            meeting_start_time: string;
                            /** Format: date-time */
                            meeting_end_time: string;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Invalid request - Validation errors (meeting_goal too short, invalid UUID) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Time slot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Slot already booked - Concurrent booking detected */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to create booking */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/my-bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all bookings for current user
         * @description Returns all bookings where the authenticated user is either the mentor or mentee, with expanded relations for mentor, mentee, and time_slot data
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user bookings with expanded relations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bookings: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                mentor_id: string;
                                /** Format: uuid */
                                mentee_id: string;
                                /** Format: uuid */
                                time_slot_id: string;
                                /** @enum {string} */
                                status: "pending" | "confirmed" | "completed" | "canceled" | "expired";
                                meeting_goal: string;
                                materials_urls: string[];
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                                time_slot: {
                                    /** Format: date-time */
                                    start_time: string;
                                    /** Format: date-time */
                                    end_time: string;
                                    /** Format: uuid */
                                    mentor_id: string;
                                };
                                mentor: {
                                    /** Format: uuid */
                                    id: string;
                                    profile: {
                                        name: string;
                                        avatar_url: string | null;
                                    };
                                };
                                mentee: {
                                    /** Format: uuid */
                                    id: string;
                                    profile: {
                                        name: string;
                                        avatar_url: string | null;
                                    };
                                };
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to fetch bookings */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/overrides/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pending tier override requests
         * @description Returns all pending tier override requests with enriched user profiles and match scores. Coordinator access only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pending tier override requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requests: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                mentee_id: string;
                                /** Format: uuid */
                                mentor_id: string;
                                reason: string;
                                /** @enum {string} */
                                status: "pending" | "approved" | "denied" | "rejected";
                                /** @enum {string} */
                                scope: "one_time";
                                /** Format: date-time */
                                expires_at: string;
                                /** Format: date-time */
                                used_at: string | null;
                                /** Format: uuid */
                                reviewed_by: string | null;
                                /** Format: date-time */
                                reviewed_at: string | null;
                                review_notes: string | null;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: uuid */
                                created_by: string | null;
                                /** Format: date-time */
                                updated_at: string;
                                /** Format: uuid */
                                updated_by: string | null;
                                mentee: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    role: string;
                                    /** @enum {string|null} */
                                    reputation_tier: "bronze" | "silver" | "gold" | "platinum" | null;
                                    profile: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        user_id: string;
                                        name: string;
                                        title: string | null;
                                        company: string | null;
                                        bio: string | null;
                                        /** Format: date-time */
                                        created_at: string;
                                        /** Format: date-time */
                                        updated_at: string;
                                    };
                                };
                                mentor: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    role: string;
                                    /** @enum {string|null} */
                                    reputation_tier: "bronze" | "silver" | "gold" | "platinum" | null;
                                    profile: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        user_id: string;
                                        name: string;
                                        title: string | null;
                                        company: string | null;
                                        bio: string | null;
                                        /** Format: date-time */
                                        created_at: string;
                                        /** Format: date-time */
                                        updated_at: string;
                                    };
                                };
                                match_score: number | null;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Forbidden - Coordinator role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Internal Server Error - Failed to fetch requests */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available matching algorithms
         * @description Returns list of available matching algorithms with their descriptions and capabilities. This endpoint queries distinct algorithm versions from the match cache for performance.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available algorithms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            algorithms: {
                                version: string;
                                label: string;
                                description: string;
                                scoreRange: string;
                                available: boolean;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Forbidden - Non-coordinator role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/users-with-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get users with match scores for specific algorithm
         * @description Returns users who have match scores cached for the specified algorithm. Useful for filtering user lists to only show users with available match data.
         */
        get: {
            parameters: {
                query?: {
                    algorithmVersion?: string;
                    role?: "mentor" | "mentee";
                    limit?: string | number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of users with match scores for the algorithm */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                /** @enum {string} */
                                role: "mentor" | "mentee" | "coordinator";
                                profile: {
                                    name: string | null;
                                } | null;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Forbidden - Non-coordinator role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/find-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get cached match recommendations
         * @description Retrieves pre-calculated match recommendations from user_match_cache. Supports filtering by algorithm version, minimum score, and result limit. Reference: FR15 (Mentor-Mentee Matching), FR16 (Match Explanation)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                        /** @enum {string} */
                        targetRole: "mentor" | "mentee";
                        options?: {
                            /** @default tag-based-v1 */
                            algorithmVersion: string;
                            /** @default 5 */
                            limit: number;
                            minScore?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Array of cached matches sorted by score DESC */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            matches: {
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    airtable_record_id: string | null;
                                    /** Format: email */
                                    email: string;
                                    /** @enum {string} */
                                    role: "mentee" | "mentor" | "coordinator";
                                    /** @enum {string} */
                                    reputation_tier?: "bronze" | "silver" | "gold" | "platinum";
                                    /** Format: date-time */
                                    created_at: string;
                                    /** Format: date-time */
                                    updated_at: string;
                                    profile: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        user_id: string;
                                        name: string;
                                        /** Format: uri */
                                        avatar_url?: string | null;
                                        title: string | null;
                                        company: string | null;
                                        bio: string | null;
                                        /** Format: date-time */
                                        created_at: string;
                                        /** Format: date-time */
                                        updated_at: string;
                                    };
                                    tags?: {
                                        /** Format: uuid */
                                        taxonomy_id: string;
                                        category: string;
                                        value: string;
                                        display_name: string;
                                    }[];
                                };
                                score: number;
                                explanation: {
                                    tagOverlap: {
                                        category: string;
                                        tag: string;
                                    }[];
                                    stageMatch: boolean;
                                    reputationCompatible: boolean;
                                    summary: string;
                                };
                            }[];
                        };
                    };
                };
                /** @description Invalid request - Validation errors */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Forbidden - Non-coordinator role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get cached match explanation
         * @description Retrieves detailed explanation for a cached match between two users. Performs bidirectional lookup (user1↔user2). Reference: FR16 (Match Explanation)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId1: string;
                        /** Format: uuid */
                        userId2: string;
                        /** @default tag-based-v1 */
                        algorithmVersion: string;
                    };
                };
            };
            responses: {
                /** @description Match explanation or null if no cached match found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            explanation: {
                                tagOverlap: {
                                    category: string;
                                    tag: string;
                                }[];
                                stageMatch: boolean;
                                reputationCompatible: boolean;
                                summary: string;
                            } | null;
                        };
                    };
                };
                /** @description Invalid request - Validation errors */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Forbidden - Non-coordinator role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description No cached match found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                timestamp: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
