name = "cf-office-hours-api"
main = "src/index.ts"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
SUPABASE_URL = "http://localhost:54321"
