name = "cf-office-hours-api"
main = "src/index.ts"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[vars]
ENVIRONMENT = "development"
SUPABASE_URL = "http://127.0.0.1:54321"
DASHBOARD_URL = "http://127.0.0.1:3000"
